apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-service
  labels:
    app: reverseproxy-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: reverseproxy-service