apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-balancer-example
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: load-balancer-example
  template:
    metadata:
      labels:
        app: load-balancer-example
    spec:
      containers:
      - image: hothanhnhank1c/udagram-frontend:v5
        name: udagram-frontend
        resources:
          limits:
            memory: 1024Mi
            cpu: "1"
          requests:
            memory: 1024Mi
            cpu: "0.2"
        ports:
        - containerPort: 8100